### ISSUE TITLE
Upgrade code to latest flutter

### ISSUE THREAD

**Issue by asashour** [Blakexx/PPoll_Redesign#3]
Thanks for sharing the code.

However, on trying to use latest flutter, there are error.

e.g. `import 'key.dart';`: Target of URI doesn't exist.

Undefined name `database`, `secretKey`, `functionsLink` and `cloudUploadDatabase`

**Comment by Blakexx** [comment]
The key.dart file is intentionally excluded from this repository. Variables are defined in key.dart when I do not wish for them to be easily accessible to the public.

Even when key.dart is included, this repository is not functional with the latest version of Flutter. I will update it eventually, but at the moment I am working on other projects. I apologize for the inconvenience.
